name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [11, 15, 16, 17]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'adopt'
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir staging && cp target/*-dist.tar.gz target/*.jar staging
      - uses: actions/upload-artifact@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          name: Package
          path: staging